trigger:
- main

variables:
  SCREENSHOT_STRATEGY: 'always'

pool:
  name: Default

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '20.x'
  displayName: 'Install Node.js'

- script: |
    echo "Installing dependencies..."
    npm install

    echo "Running tests..."
    npm run test || echo "Tests failed"
  displayName: 'npm install and test'
  continueOnError: true

- task: PublishPipelineArtifact@1
  displayName: '📄 Publish HTML Test Report'
  inputs:
    targetPath: '$(System.DefaultWorkingDirectory)/reports'
    artifact: 'TestExecution_Report'
