trigger:
- main

variables:
  SCREENSHOT_STRATEGY: 'always'

pool:
  agent: Default

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '20.x'
  displayName: 'Install Node.js'

- script: |
    npm install
    npm run test
  displayName: 'npm install and test'

# ✅ Step to publish HTML report as a downloadable artifact
- task: PublishPipelineArtifact@1
  displayName: 'Publish HTML Test Report'
  inputs:
    targetPath: '$(System.DefaultWorkingDirectory)/reports'
    artifact: 'TestExecution_Report'
